import { ClothingItem, Outfit, WeatherData, OutfitSuggestion } from '@/types';

export const mockWeather: WeatherData = {
  temperature: 31,
  feels_like: 36,
  description: 'Humid and sunny',
  humidity: 84,
  wind_speed: 12,
  city: 'Singapore',
  icon: '01d',
  condition: 'hot',
};

export const mockClothingItems: ClothingItem[] = [
  {
    id: '1',
    user_id: 'user1',
    name: 'White Oxford Shirt',
    category: 'shirt',
    color_hex: '#FFFFFF',
    color_name: 'White',
    image_url: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400',
    tags: ['office', 'smart_casual', 'date_night'],
    times_worn: 8,
    last_worn: '2026-05-10',
    created_at: '2026-01-01',
  },
  {
    id: '2',
    user_id: 'user1',
    name: 'Navy Chino Pants',
    category: 'pants',
    color_hex: '#1E2A38',
    color_name: 'Navy',
    image_url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400',
    tags: ['office', 'smart_casual'],
    times_worn: 12,
    last_worn: '2026-05-08',
    created_at: '2026-01-01',
  },
  {
    id: '3',
    user_id: 'user1',
    name: 'Beige Linen Shirt',
    category: 'shirt',
    color_hex: '#D8C7A3',
    color_name: 'Beige',
    image_url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400',
    tags: ['casual', 'weekend', 'travel'],
    times_worn: 5,
    last_worn: '2026-05-05',
    created_at: '2026-01-15',
  },
  {
    id: '4',
    user_id: 'user1',
    name: 'Black Slim Pants',
    category: 'pants',
    color_hex: '#2B2B2B',
    color_name: 'Charcoal Black',
    image_url: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=400',
    tags: ['office', 'date_night', 'luxury'],
    times_worn: 15,
    last_worn: '2026-05-11',
    created_at: '2026-01-01',
  },
  {
    id: '5',
    user_id: 'user1',
    name: 'White Leather Sneakers',
    category: 'sneakers',
    color_hex: '#F5F5F5',
    color_name: 'Off-White',
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    tags: ['casual', 'weekend', 'minimal'],
    times_worn: 20,
    last_worn: '2026-05-12',
    created_at: '2026-01-01',
  },
  {
    id: '6',
    user_id: 'user1',
    name: 'Silver Watch',
    category: 'watch',
    color_hex: '#C0C0C0',
    color_name: 'Silver',
    image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400',
    tags: ['office', 'smart_casual', 'luxury', 'date_night'],
    times_worn: 30,
    last_worn: '2026-05-12',
    created_at: '2026-01-01',
  },
  {
    id: '7',
    user_id: 'user1',
    name: 'Olive Bomber Jacket',
    category: 'jacket',
    color_hex: '#556B2F',
    color_name: 'Olive',
    image_url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400',
    tags: ['casual', 'weekend', 'travel'],
    times_worn: 7,
    last_worn: '2026-04-28',
    created_at: '2026-02-01',
  },
  {
    id: '8',
    user_id: 'user1',
    name: 'Dark Brown Oxford Shoes',
    category: 'shoes',
    color_hex: '#4A2C0A',
    color_name: 'Dark Brown',
    image_url: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=400',
    tags: ['office', 'smart_casual', 'luxury'],
    times_worn: 10,
    last_worn: '2026-05-09',
    created_at: '2026-01-01',
  },
];

export const mockTodaySuggestion: OutfitSuggestion = {
  outfit: {
    shirt: mockClothingItems[0],
    pants: mockClothingItems[1],
    shoes: mockClothingItems[7],
    watch: mockClothingItems[5],
  },
  color_pairs: [
    { item1: 'Shirt', hex1: '#FFFFFF', item2: 'Pants', hex2: '#1E2A38' },
    { item1: 'Shoes', hex1: '#4A2C0A', item2: 'Watch', hex2: '#C0C0C0' },
  ],
  occasion: 'office',
  reason:
    'A classic white shirt paired with navy chinos is timeless for office days. The warm weather calls for breathable fabrics, and brown oxfords add polish.',
  style_tip: 'Roll up your sleeves slightly for a relaxed yet professional look.',
};

export const mockOutfitHistory: Outfit[] = [
  {
    id: 'o1',
    user_id: 'user1',
    name: 'Monday Office Look',
    items: [mockClothingItems[0], mockClothingItems[1], mockClothingItems[7]],
    occasion: 'office',
    color_palette: [
      { hex: '#FFFFFF', name: 'White' },
      { hex: '#1E2A38', name: 'Navy' },
      { hex: '#4A2C0A', name: 'Brown' },
    ],
    ai_reason: 'Perfect smart casual for a Monday meeting.',
    worn_date: '2026-05-11',
    created_at: '2026-05-11',
  },
  {
    id: 'o2',
    user_id: 'user1',
    name: 'Weekend Casual',
    items: [mockClothingItems[2], mockClothingItems[4], mockClothingItems[6]],
    occasion: 'casual',
    color_palette: [
      { hex: '#D8C7A3', name: 'Beige' },
      { hex: '#F5F5F5', name: 'Off-White' },
      { hex: '#556B2F', name: 'Olive' },
    ],
    ai_reason: 'Earthy tones for a relaxed weekend out.',
    worn_date: '2026-05-10',
    created_at: '2026-05-10',
  },
  {
    id: 'o3',
    user_id: 'user1',
    name: 'Evening Dinner',
    items: [mockClothingItems[0], mockClothingItems[3], mockClothingItems[7], mockClothingItems[5]],
    occasion: 'date_night',
    color_palette: [
      { hex: '#FFFFFF', name: 'White' },
      { hex: '#2B2B2B', name: 'Black' },
      { hex: '#4A2C0A', name: 'Brown' },
    ],
    ai_reason: 'Monochrome base with a classic white shirt — always sharp for evenings.',
    worn_date: '2026-05-08',
    created_at: '2026-05-08',
  },
];
