import { NextRequest, NextResponse } from 'next/server';
import { aiChat, aiChatText, safeParseJSON } from '@/lib/ai-client';

const GITHUB_OWNER = 'harsaikron';
const GITHUB_REPO  = 'Wearly';

// Files the AI is allowed to read and modify (UI/styling only — never API or config)
const READABLE_FILES = [
  'src/app/globals.css',
  'src/app/page.tsx',
  'src/app/wardrobe/page.tsx',
  'src/app/stylist/page.tsx',
  'src/components/Navbar.tsx',
  'src/components/ClothingCard.tsx',
  'src/components/UploadZone.tsx',
  'src/components/Camera.tsx',
];

// ─── GitHub helpers ───────────────────────────────────────────────────────────

function ghHeaders(token: string) {
  return {
    Authorization: `token ${token}`,
    Accept: 'application/vnd.github.v3+json',
    'Content-Type': 'application/json',
  };
}

async function ghGet(path: string, token: string) {
  const res = await fetch(`https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/${path}`, {
    headers: ghHeaders(token),
  });
  if (!res.ok) throw new Error(`GitHub GET ${path} → ${res.status}`);
  return res.json();
}

async function ghPost(path: string, body: unknown, token: string) {
  const res = await fetch(`https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/${path}`, {
    method: 'POST',
    headers: ghHeaders(token),
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const err = await res.text();
    throw new Error(`GitHub POST ${path} → ${res.status}: ${err}`);
  }
  return res.json();
}

async function getFile(filePath: string, token: string): Promise<{ content: string; sha: string }> {
  const data = await ghGet(`contents/${filePath}`, token);
  return {
    content: Buffer.from(data.content as string, 'base64').toString('utf-8'),
    sha: data.sha as string,
  };
}

async function createPR(
  token: string,
  headSha: string,
  branchName: string,
  changes: { file: string; newContent: string }[],
  prTitle: string,
  prBody: string,
  reviewComment: string
): Promise<{ url: string; number: number }> {

  // 1. Get current tree SHA
  const commit = await ghGet(`git/commits/${headSha}`, token);
  const baseTreeSha = commit.tree.sha as string;

  // 2. Create blobs for each changed file
  const treeEntries = await Promise.all(
    changes.map(async (c) => {
      const blob = await ghPost('git/blobs', { content: c.newContent, encoding: 'utf-8' }, token);
      return { path: c.file, mode: '100644', type: 'blob', sha: blob.sha };
    })
  );

  // 3. Create new tree
  const newTree = await ghPost('git/trees', { base_tree: baseTreeSha, tree: treeEntries }, token);

  // 4. Create commit
  const newCommit = await ghPost('git/commits', {
    message: `feat: ${prTitle}\n\nAuto-generated by Wearly AI Evolution (Gemma 4)`,
    tree:    newTree.sha,
    parents: [headSha],
  }, token);

  // 5. Create branch
  await ghPost('git/refs', {
    ref: `refs/heads/${branchName}`,
    sha: newCommit.sha,
  }, token);

  // 6. Create PR
  const pr = await ghPost('pulls', {
    title: prTitle,
    body:  prBody,
    head:  branchName,
    base:  'main',
  }, token);

  // 7. Post AI review comment
  await ghPost(`pulls/${pr.number}/reviews`, {
    body:  reviewComment,
    event: 'COMMENT',
  }, token);

  return { url: pr.html_url as string, number: pr.number as number };
}

// ─── Main handler ─────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  const token = process.env.GITHUB_TOKEN;

  const { feedback } = await req.json() as { feedback: string };
  if (!feedback?.trim()) {
    return NextResponse.json({ error: 'Feedback is required.' }, { status: 400 });
  }

  try {
    // 1. Read source files — from GitHub if token available, else import local files
    const fileContents: Record<string, string> = {};

    if (token) {
      await Promise.allSettled(
        READABLE_FILES.map(async (f) => {
          try {
            const { content } = await getFile(f, token);
            fileContents[f] = content;
          } catch { /* skip */ }
        })
      );
    }
    // In preview mode (no token) we proceed with an empty fileContents;
    // the AI is prompted with the app description instead of actual code.

    const APP_DESCRIPTION = `Wearly is an AI wardrobe portal for men in Singapore.
Stack: Next.js 16 App Router, TypeScript, Tailwind CSS, Zustand, lucide-react icons.
CSS variables: --background #f5f6fa, --card #ffffff, --card-border #e4e7ef, --accent #6366f1, --muted #8b93a7, --accent-muted rgba(99,102,241,0.08), --muted-bg #f0f2f8, --shadow-sm, --shadow-md.
Pages: / (home — weather strip, events widget, AI stylist chat), /wardrobe (clothing grid), /stylist (detailed chat), /evolve (this page).
Components: Navbar.tsx, ClothingCard.tsx, Camera.tsx, OllamaStatus.tsx.
Store: useWardrobeStore() with items array of { id, name, category, color_hex, color_name, tags }.`;

    const codeContext = Object.keys(fileContents).length > 0
      ? Object.entries(fileContents)
          .map(([p, code]) => `=== ${p} ===\n${code.slice(0, 3000)}`)
          .join('\n\n')
      : `App description (no source access in preview mode):\n${APP_DESCRIPTION}`;

    // 2. Ask AI to analyze feedback and plan code changes
    const analysisSystem = `You are an expert Next.js/React developer working on "Wearly" — an AI wardrobe portal.
Analyze user feedback and output precise, working code changes.
App stack: Next.js App Router, TypeScript, Tailwind CSS, Zustand, CSS variables for theming.
Color scheme: background #f5f6fa, card #ffffff, accent #6366f1 (indigo), muted #8b93a7.

IMPORTANT: Output valid JSON only. No markdown fences. No explanations outside JSON.
{
  "pr_title": "short imperative title under 60 chars",
  "pr_description": "markdown description of what changed and why",
  "files_changed": ["src/path/to/file.tsx"],
  "changes": [
    {
      "file": "src/app/...",
      "summary": "one sentence: what changes in this file",
      "new_content": "complete updated file content — valid TypeScript/CSS"
    }
  ]
}

Rules:
- Only modify files: ${READABLE_FILES.join(', ')}
- Maximum 2 files per PR
- Preserve imports/types/functionality unless explicitly asked to change
- Keep same code style and CSS variable references
- new_content must be the COMPLETE file, not a snippet`;

    const analysisMessage = `User feedback: "${feedback}"

Current codebase:
${codeContext}

Generate precise code changes.`;

    const { text: analysisRaw } = await aiChat(analysisSystem, analysisMessage, {
      temperature: 0.3,
      maxTokens: 6000,
    });

    let analysis: {
      pr_title: string;
      pr_description: string;
      files_changed: string[];
      changes: { file: string; summary: string; new_content: string }[];
    };

    try {
      analysis = safeParseJSON(analysisRaw) as typeof analysis;
    } catch {
      return NextResponse.json(
        { error: 'AI failed to generate structured changes. Try rephrasing your feedback.' },
        { status: 422 }
      );
    }

    if (!analysis.changes?.length) {
      return NextResponse.json(
        { error: 'AI could not determine what to change for this feedback. Try being more specific.' },
        { status: 422 }
      );
    }

    // 3. AI review comment
    const reviewSystem = `You are a senior code reviewer for the Wearly app. Write a concise PR review.
Cover: what changed, why it's a good solution, edge cases to watch.
Under 150 words. Professional but friendly.`;

    const { text: reviewComment } = await aiChatText(
      reviewSystem,
      `PR: ${analysis.pr_title}\nFiles: ${analysis.changes.map((c) => c.file).join(', ')}\nRequest: "${feedback}"\n\nWrite review:`,
      { temperature: 0.5, maxTokens: 250 }
    );

    // ── Preview mode (no GitHub token) ───────────────────────────────────────
    if (!token) {
      return NextResponse.json({
        preview: {
          pr_title:        analysis.pr_title,
          files_changed:   analysis.files_changed ?? analysis.changes.map((c) => c.file),
          review_comment:  reviewComment,
          preview_changes: analysis.changes.map((c) => ({ file: c.file, summary: c.summary ?? 'updated' })),
        },
      });
    }

    // ── Full PR mode ─────────────────────────────────────────────────────────
    const refData = await ghGet('git/ref/heads/main', token);
    const headSha = refData.object.sha as string;

    const branchName = `evolve/${Date.now()}-${analysis.pr_title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .slice(0, 40)}`;

    const { url: prUrl, number: prNumber } = await createPR(
      token,
      headSha,
      branchName,
      analysis.changes.map((c) => ({ file: c.file, newContent: c.new_content })),
      analysis.pr_title,
      `## Summary\n\n${analysis.pr_description}\n\n---\n> 🤖 Auto-generated by **Wearly AI Evolution**\n>\n> **User feedback:** "${feedback}"`,
      reviewComment
    );

    return NextResponse.json({
      pr_url:         prUrl,
      pr_number:      prNumber,
      pr_title:       analysis.pr_title,
      pr_description: analysis.pr_description,
      files_changed:  analysis.files_changed ?? analysis.changes.map((c) => c.file),
      review_comment: reviewComment,
      branch:         branchName,
    });

  } catch (err) {
    console.error('[evolve]', err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : 'Evolution failed.' },
      { status: 500 }
    );
  }
}
