"""
Step 3 — Export Fine-tuned Model to GGUF + Load into Ollama
=============================================================
Converts the trained LoRA adapter + base model into GGUF format
that Ollama can load as a first-class model.

Quantization levels:
  Q4_K_M  — best balance of size/quality (recommended, ~5 GB)
  Q5_K_M  — slightly better quality     (~6 GB)
  Q8_0    — near-full quality           (~9 GB)
  F16     — full precision (for eval)   (~16 GB)

Usage:
  python 3_export.py --model checkpoints/wearly-gemma4-clothing-*/final

  # Custom quantization
  python 3_export.py --model checkpoints/*/final --quant Q5_K_M

  # Export + auto-register with Ollama
  python 3_export.py --model checkpoints/*/final --ollama
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

GGUF_OUTPUT_DIR = "gguf_exports"
OLLAMA_MODEL_NAME = "wearly-fashion-v1"
DEFAULT_QUANT = "Q4_K_M"

MODELFILE_TEMPLATE = """\
# Wearly Clothing Classifier — Gemma 4 fine-tuned with Unsloth
# Generated by fine-tuning/module1-clothing-classifier/3_export.py

FROM {gguf_path}

SYSTEM \"\"\"You are Wearly's clothing classifier AI, fine-tuned on thousands of fashion items.
For every clothing image, return ONLY valid JSON with these exact fields:
- suggested_name: concise item name (e.g. "Navy Slim Chinos")
- category: one of shirt|formal_shirt|tshirt|pants|jeans|shorts|shoes|sneakers|loafers|jacket|watch|belt|accessory
- color_hex: dominant color as 6-digit hex (e.g. "#1A237E")
- color_name: human-readable color name (e.g. "Navy Blue")
- tags: array from [office, casual, date_night, weekend, smart_casual, minimal, luxury, travel, festive, gym]

Return ONLY the JSON object. No markdown. No explanation.\"\"\"

PARAMETER temperature 0.1
PARAMETER top_p 0.9
PARAMETER top_k 40
PARAMETER num_predict 256
PARAMETER stop "<end_of_turn>"
PARAMETER stop "<eos>"
"""


def find_latest_checkpoint(output_dir: str = "checkpoints") -> str | None:
    """Find the most recently trained model directory."""
    checkpoints = sorted(Path(output_dir).glob("wearly-gemma4-clothing-*/final"))
    return str(checkpoints[-1]) if checkpoints else None


def merge_and_export(
    model_path: str,
    quant: str = DEFAULT_QUANT,
    output_dir: str = GGUF_OUTPUT_DIR,
    register_ollama: bool = False,
) -> str:
    """Merge LoRA weights into base model and export as GGUF."""

    try:
        from unsloth import FastLanguageModel
    except ImportError:
        print("✗ Unsloth not installed. Run: pip install -r requirements.txt")
        sys.exit(1)

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    gguf_name = f"wearly-gemma4-clothing-{quant.lower()}.gguf"
    gguf_path = out / gguf_name

    print(f"\nLoading fine-tuned model from {model_path}…")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name     = model_path,
        max_seq_length = 1024,
        load_in_4bit   = True,
    )

    print(f"Exporting to GGUF ({quant}) → {gguf_path}…")
    model.save_pretrained_gguf(
        str(out / f"wearly-gemma4-clothing-{quant.lower()}"),
        tokenizer,
        quantization_method = quant,
    )

    # Unsloth names the file automatically; find it
    candidates = list(out.glob(f"*{quant.lower()}*.gguf"))
    if candidates:
        actual_gguf = candidates[0]
        if actual_gguf != gguf_path:
            shutil.move(str(actual_gguf), str(gguf_path))
        print(f"✓ GGUF saved: {gguf_path}  ({gguf_path.stat().st_size / 1e9:.1f} GB)")

    # Write Ollama Modelfile
    modelfile_content = MODELFILE_TEMPLATE.format(gguf_path=str(gguf_path.absolute()))
    modelfile_path = out / "Modelfile"
    modelfile_path.write_text(modelfile_content)
    print(f"✓ Modelfile written: {modelfile_path}")

    if register_ollama:
        _register_with_ollama(str(gguf_path.absolute()), modelfile_path)

    return str(gguf_path)


def _register_with_ollama(gguf_path: str, modelfile_path: Path) -> None:
    """Register the GGUF model with local Ollama."""
    print(f"\nRegistering with Ollama as '{OLLAMA_MODEL_NAME}'…")

    # Check Ollama is running
    try:
        result = subprocess.run(
            ["curl", "-s", "http://localhost:11434/api/tags"],
            capture_output=True, text=True, timeout=5
        )
        if result.returncode != 0:
            print("⚠ Ollama not running. Start with: ollama serve")
            print(f"  Then manually run: ollama create {OLLAMA_MODEL_NAME} -f {modelfile_path}")
            return
    except Exception:
        print("⚠ Could not reach Ollama at http://localhost:11434")
        return

    # Create model in Ollama
    result = subprocess.run(
        ["ollama", "create", OLLAMA_MODEL_NAME, "-f", str(modelfile_path)],
        capture_output=True, text=True
    )

    if result.returncode == 0:
        print(f"✓ Ollama model '{OLLAMA_MODEL_NAME}' created successfully")
        print(f"\nTest it:")
        print(f"  ollama run {OLLAMA_MODEL_NAME}")
        print(f"\nWearly will auto-detect it. Restart npm run dev to pick it up.")
    else:
        print(f"✗ Ollama create failed: {result.stderr}")
        print(f"  Manual command: ollama create {OLLAMA_MODEL_NAME} -f {modelfile_path}")


def verify_gguf(gguf_path: str) -> None:
    """Quick sanity check on the GGUF file."""
    p = Path(gguf_path)
    if not p.exists():
        print(f"✗ GGUF not found: {gguf_path}")
        return

    size_gb = p.stat().st_size / 1e9
    print(f"\nGGUF Verification:")
    print(f"  File  : {p.name}")
    print(f"  Size  : {size_gb:.2f} GB")
    print(f"  Path  : {p.absolute()}")

    # Read GGUF magic bytes
    with open(p, "rb") as f:
        magic = f.read(4)
    if magic == b"GGUF":
        print(f"  Magic : ✓ GGUF")
    else:
        print(f"  Magic : ✗ Unexpected bytes {magic!r}")

    print(f"\nNext step: python 4_evaluate.py --gguf {gguf_path}")


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export Wearly fine-tuned model to GGUF")
    parser.add_argument("--model",      type=str, default=None,         help="Path to fine-tuned model directory")
    parser.add_argument("--quant",      type=str, default=DEFAULT_QUANT, help="GGUF quantization (Q4_K_M, Q5_K_M, Q8_0, F16)")
    parser.add_argument("--output-dir", type=str, default=GGUF_OUTPUT_DIR, help="Output directory for GGUF files")
    parser.add_argument("--ollama",     action="store_true",            help="Auto-register with local Ollama after export")
    parser.add_argument("--verify",     type=str, default=None,         help="Verify an existing GGUF file")
    args = parser.parse_args()

    if args.verify:
        verify_gguf(args.verify)
        sys.exit(0)

    model_path = args.model
    if model_path is None:
        model_path = find_latest_checkpoint()
        if model_path is None:
            print("No checkpoint found. Run: python 2_train.py")
            sys.exit(1)
        print(f"Using latest checkpoint: {model_path}")

    gguf_path = merge_and_export(
        model_path     = model_path,
        quant          = args.quant,
        output_dir     = args.output_dir,
        register_ollama = args.ollama,
    )

    verify_gguf(gguf_path)
